name: biases-sk-speech
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pytorch::pytorch=2.1.0
  - pytorch::torchaudio=2.1.0
  - pytorch::pytorch-cuda=11.8
  - torchmetrics=1.2.1
  - transformers=4.35.2
  - datasets=2.15.0
  - accelerate=0.25.0
  - click=8.1.7
  - tqdm=4.66.1
  - scipy=1.11.4
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - numpy
  - pandas
  - joblib
  - pip
  - pip:
    - openai-whisper=20231117